INSERT INTO [TABELA DE CLIENTES]
{[CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PREÇO DE LISTA])
VALUES
('46177891', 'Light-350ml-Melancia', 'Lata', '350 ml', 'Melancia', 4.50)

INSERT INTO [TABELA DE CLIENTES]
{[CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PREÇO DE LISTA])
VALUES
('48676177', 'Light-350ml-Melão', 'Lata', '350 ml', 'Melão', 4.50)