UPDATE [TABELA DE PRODUTOS] SET
[EMBALAGEM] = 'Lata',
[PREÇO DE LISTA] = 2.46,
WHERE [CODIGO DO PRODUTO] = '544931'

UPDATE[TABELA DE PRODUTOS] SET
[EMBALAGEM] = 'Garrafa',
WHERE [CODIGO DO PRODUTO] = '1045175'



DELETE FROM [TABELA DE PRODUTOS] 
WHERE [CODIGO DO PRODUTO] = '544931'

DELETE FROM [TABELA DE PRODUTOS] 
WHERE [CODIGO DO PRODUTO] = '1045175'