SELECT * FROM [TABELA DE CLIENTES]

SELECT *  FROM [SUCOS_VENDAS].[dbo].[ITENS NOTAS FISCAIS]

SELECT *  FROM [SUCOS_VENDAS].[dbo].[NOTAS FISCAIS]

SELECT * FROM [NOTAS FISCAIS]  AS NF INNER JOIN [ITENS NOTAS FISCAIS] AS INF
ON NF.NUMERO = INF.NUMERO

SELECT NF.CPF, SUBSTRING(CONVERT(VARCHAR,NF.[DATA],120),1,7) AS ANO_MES, INF.QUANTIDADE FROM [NOTAS FISCAIS]  AS NF INNER JOIN [ITENS NOTAS FISCAIS] AS INF
ON NF.NUMERO = INF.NUMERO

SELECT NF.CPF, SUBSTRING(CONVERT(VARCHAR,NF.[DATA],120),1,7) AS ANO_MES, SUM(INF.QUANTIDADE) AS QUANTIDADE_MES FROM [NOTAS FISCAIS]  AS NF 
INNER JOIN [ITENS NOTAS FISCAIS] AS INF
ON NF.NUMERO = INF.NUMERO
GROUP BY NF.CPF, SUBSTRING(CONVERT(VARCHAR,NF.[DATA],120),1,7)

SELECT TC.NOME, TC.[VOLUME DE COMPRA] FROM [TABELA DE CLIENTES] AS TC



SELECT TC.NOME, CQ.ANO_MES, CQ.QUANTIDADE_MES, TC.[VOLUME DE COMPRA]
FROM
(SELECT NF.CPF, SUBSTRING(CONVERT(VARCHAR,NF.[DATA],120),1,7) AS ANO_MES, SUM(INF.QUANTIDADE) AS QUANTIDADE_MES FROM [NOTAS FISCAIS]  AS NF 
INNER JOIN [ITENS NOTAS FISCAIS] AS INF
ON NF.NUMERO = INF.NUMERO
GROUP BY NF.CPF, SUBSTRING(CONVERT(VARCHAR,NF.[DATA],120),1,7)) CQ
INNER JOIN [TABELA DE CLIENTES] AS TC ON TC.CPF=CQ.CPF

--VERIFICANDO STATUS DE VENDA
SELECT AUX1.NOME, AUX1.ANO_MES, AUX1.QUANTIDADE_MES,
CASE WHEN AUX1.QUANTIDADE_MES <= AUX1.[VOLUME DE COMPRA] THEN 'VENDA VÁLIDA'
	 WHEN AUX1.QUANTIDADE_MES > AUX1.[VOLUME DE COMPRA] THEN 'VENDA INVÁLIDA'
END AS STATUS_VENDA
FROM
(SELECT TC.NOME, CQ.ANO_MES, CQ.QUANTIDADE_MES, TC.[VOLUME DE COMPRA]
FROM
(SELECT NF.CPF, SUBSTRING(CONVERT(VARCHAR,NF.[DATA],120),1,7) AS ANO_MES, SUM(INF.QUANTIDADE) AS QUANTIDADE_MES FROM [NOTAS FISCAIS]  AS NF 
INNER JOIN [ITENS NOTAS FISCAIS] AS INF
ON NF.NUMERO = INF.NUMERO
GROUP BY NF.CPF, SUBSTRING(CONVERT(VARCHAR,NF.[DATA],120),1,7)) CQ
INNER JOIN [TABELA DE CLIENTES] AS TC ON TC.CPF=CQ.CPF) AUX1
ORDER BY AUX1.NOME, AUX1.ANO_MES

--