SELECT * FROM [dbo].[TABELA DE PRODUTOS]

--ORDENACAO ASCENDENTE
SELECT * FROM [TABELA DE PRODUTOS] ORDER BY [PREÇO DE LISTA]

--ORDENACAO DESCENDENTE
SELECT * FROM [TABELA DE PRODUTOS] ORDER BY [PREÇO DE LISTA] DESC

--ORDENACAO POR 1 CAMPO
SELECT * FROM [TABELA DE PRODUTOS] ORDER BY [NOME DO PRODUTO]

--ORDENACAO POR 2 CAMPOS
SELECT [EMBALAGEM], [NOME DO PRODUTO] FROM [TABELA DE PRODUTOS] 
ORDER BY [EMBALAGEM], [NOME DO PRODUTO]

--1o CAMPO DESC, 2O CAMPO ASC
SELECT [EMBALAGEM], [NOME DO PRODUTO] FROM [TABELA DE PRODUTOS] 
ORDER BY [EMBALAGEM] DESC, [NOME DO PRODUTO] ASC