CREATE DATABASE [VENDAS SUCOS]

CREATE DATABASE [VENDAS SUCOS 2]
ON (NAME = VENDAS_SUCOS_2_DAT, --NOME LÓGICO DO BD
FILENAME = 'C:\TEMP\DATA\VENDAS_SUCOS_02.MDF', --LOCAL ONDE SERÁ SALVO, MDF = ARQUIVO MASTER DE DADOS
SIZE = 10, --TAMANHO INICIAL DE 10MB
MAXSIZE = 50, --TAMANHO MÁX COM DADOS É 50MB
FILEGROWTH = 5) --CRESCE DE 5 EM 5 MB

LOG ON (NAME = VENDAS_SUCOS_2_LOG,
FILENAME = 'C:\TEMP\DATA\VENDAS_SUCOS_02.LDF', --LOCAL ONDE SERÁ SALVO, LDF = arquivo que armazena todos os logs/eventos de transações que são executados no banco de dados.
SIZE = 10,
MAXSIZE = 50,
FILEGROWTH = 5)

DROP DATABASE [VENDAS SUCOS 2]

